name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - develop

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/backend.yaml

  frontend:
    name: Frontend
    uses: ./.github/workflows/frontend.yaml